### ISSUE TITLE
[Bug Report] Configured Coding Languages are not Highlighted

### ISSUE THREAD

**Issue by kevinmatthes** [vigna/ne#104]
Due to the syntax highlighting being controlled by the documentation file, ll. 4510, there are various coding languages which are configured with a highlighting scheme but are not activated.  These languages can be activated by adding them to the example beginning on line 4510 in `doc/ne.texinfo`.

Here are the languages I found so far.  I named the file extensions I know to be related to the respective language.  The **bold** extensions are tested with version 3.1.2 from 6th October 2018.  Due to the latest changes to this line sequence being older (the latest change to this section was committed in February 2017, according to the GitHub blame on this region), this list should still be accurate.

* Git commit messages (**`COMMIT_EDITMSG`**)
* Go (`go`)
* Haskell (**`hs`**, `lhs`)
* Lua (`lua`)
* PHP (`php`)
* TOML (**`toml`**)

This issue is primarily intended to collect further languages which have a configuration file in `syntax/` but no entry in `doc/ne.texinfo`.  As soon as some further languages are identified, I am going to submit a Pull Request.

**Comment by utoddl** [comment]
The Haskell extensions `hs` and `lhs` certainly should be added. But there's no benefit to adding to the extensions map `go`, `lua`, `php`, `toml`, or anything else where the existing `.jsf` file's basename matches the document's extension.

BTW, there are two other ways to get a particular `.jsf` mapped to a different extension. One is to create appropriate symlinks in either `~/.ne/syntax` or `$NE_GLOBAL_DIR/syntax` (which admittedly is kind of bizarre). The other more normal way is to add the necessary `Syntax` command to the given extension's AutoPrefs file: `~/.ne/…#ap`.
