### ISSUE TITLE
[Feature Request] copy current line

### ISSUE THREAD

**Issue by Herr-Sepp** [vigna/ne#107]
I hope i did not miss it but i would love the feature to copy the current line in which the cursor is, directly below it.
In some IDE this is bound to Ctrl+D

Thanks for this great editor!

**Comment by vigna** [comment]
You can do delete line (^-Y) followed by two undelete line (^-U).

**Comment by Herr-Sepp** [comment]
A creative solution I had not thought of. Thank you
Should I leave the ticket open as a feature request for direct support?
