### ISSUE TITLE
Link in Wiki to Website ist broken

### ISSUE THREAD

**Issue by mindforger** [vigna/ne#11]
i just wanted you to know that the Link on the Wiki
https://wiki.python.org/moin/PythonEditors
to your website ist broken!

it is stating ne.d**s**i.unimi.it/ with a spare "s" ... sorry i am not into wikis enough to resolve this myself, sorry

**Comment by utoddl** [comment]
Thank you for letting us know about the broken link. It's fixed now. Had to get an account on their site to fix it, but it's done.
