### ISSUE TITLE
copy-paste doesn't work well

### ISSUE THREAD

**Issue by mariusa** [vigna/ne#110]
Hi,

Running gnome, I tried
ne a.txt
write "text"
Ctrl+B , arrow down, Ctrl+X. "text" was cut

Ctrl+V: another text was pasted, that I earlier copied from Chrome browser with Ctrl+C.

I have `xclip` installed, if relevant.

**Comment by utoddl** [comment]
Did you ever figure out what's going on?
The behavior you describe is what you should see with Ctrl+Shift+V, but Ctrl+V should be passed on into the application.
Perhaps you've assigned Ctrl+V as a keyboard shortcut to `xclip`, in which case no terminal application will see Ctrl+V (which would be bad; don't do that).
