### ISSUE TITLE
compile ne for RiskV64

### ISSUE THREAD

**Issue by fabriziotappero** [vigna/ne#114]
hello, I'd like to cross compile ne for a RiscV64 architecture. This is my starting point
https://github.com/milkv-duo/duo-examples

I am preparing a crosscompile env using 
```
source envsetup.sh
```
which simply sets a custom gcc cross compile prefix:
```
CC = $(TOOLCHAIN_PREFIX)gcc
```
and I can successfully compile the examples above. Attempting the same with ne I get:

```
$ make
( cd doc; make )
make[1]: Entering directory 'ne/doc'
makeinfo ne.texinfo
make[1]: makeinfo: No such file or directory
make[1]: *** [makefile:27: ne.info.gz] Error 127
make[1]: Leaving directory 'ne/doc'
make: *** [makefile:33: docs] Error 2
```
I did try the simplest option:
```
cd src
make NE_TERMCAP=1 NE_ANSI=1 CC=$(TOOLCHAIN_PREFIX)gcc
```

Any help?

**Comment by vigna** [comment]
Well, you need makeinfo installed...

**Comment by fabriziotappero** [comment]
Hi Sebastiano,
thanks for your help.

I did install makeinfo with `sudo apt install textinfo` and with:

```
cd src
make NE_TERMCAP=1 NE_ANSI=1 CC=riscv64-unknown-linux-musl-gcc
```

I did successfully compile it. 
thanks.

**Comment by vigna** [comment]
If you have terminfo you can compile the terminfo version, which is theory is better...
