### ISSUE TITLE
[Feature Request] Soft wrapping Flag.

### ISSUE THREAD

**Issue by wiviw5** [vigna/ne#117]
I looked through Issues, PRs, and outside of this repo and only found [one](https://www.reddit.com/r/linuxquestions/comments/aklekq/ne_nice_editor_soft_line_wrapping_available/) instance of this feature being mentioned before that I could find. (If this has been discussed on the mailing group before, please let me know and the status of that discussion, I was unable to search through it, but this is likely only due to my unfamiliarity with mail groups since they were before my time.)

The Word Wrap is a great feature, but I do think that this application could benefit from soft wrapping as well. Hard Wrapping is what is currently implemented with Word Wrap, but if we had either another flag or a 3rd option on WordWrap for soft wrapping that kept everything on the same line I think it would benefit this program greatly.

It would act similarly to how WordWrap currently functions (relying on either the same guess at 0/variable from RightMargin) and only visually shows the long line as wrapped down to the next line. It could be denoted with a capital W instead of the lowercase w currently used for hard wrap in the status bar.

One issue however with this is determining whether or not a new line is either soft wrapped or a real new line. A solution could be to have some way to show a "faked" new line. Perhaps showing a character like "←" right before the soft wrapped new line could signify this occurred for users who may have accidentally turned this on, or who would just like to know where the newlines actually lie as well.

An example of how this would look in practice:

```
A really long line going on and on
←and soft wrapped onto the next line
```

I'm unfortunately not at all literate in C code, so I'm not sure about the difficulty it would be with implementation at any step of this process.

Thank you for reading into this feature request/suggestion. I think it'd be an excellent addition to this already great piece of software, and as a brief background, I was told about this project by a friend while I was looking for a "no nonsense" command line editor that had keybindings I was familiar with rather than having to learn vim/neovim/emacs or to deal with nano's horrible keybindings and I was not disappointed by this project with everything being super well implemented and especially light.

**Comment by vigna** [comment]
That's the most requested feature, I think, with proper block highlighting. The problem is that the design of the editor makes soft wrapping basically impossible wihtout a major, if not complete, rewrite. All operations are tied to a matrix model in which line and column represent a position in the text.
