### ISSUE TITLE
YAML comments syntax highlighting

### ISSUE THREAD

**Issue by jooadam** [vigna/ne#13]
As per the [YAML specification](http://www.yaml.org/spec/1.2/spec.html#id2780069):

> Comments must be separated from other tokens by white space characters.

The current syntax highlighting for YAML does not require whitespace to be present before the # sign, visually breaking lines containing e.g. filenames like ne’s own autoprefs.

**Comment by utoddl** [comment]
The latest commits to the master branch contain fixes for YAML comments and to make ne map the "yml" extension to the "yaml.jsf" highlighter.
