### ISSUE TITLE
Defining Home and End in the menus

### ISSUE THREAD

**Issue by jooadam** [vigna/ne#16]
I instinctively try to use Home and End in the menus to get to the first and last menu, respectively, but they are not defined, sadly.

I think they would complement the existing navigation options nicely.

**Comment by utoddl** [comment]
I quite agree. Done. Also the Tab key now advances to the next menu.

**Comment by jooadam** [comment]
Great, thanks. Although this only enables navigation with Ctrl-a / Ctrl-e using the default key bindings (I suppose you have rebound Home/End to MoveSOL/MoveEOL), since Home/End are bound to MoveIncUp/MoveIncDown by default. So pressing Home/End will still just close the menu.
