### ISSUE TITLE
Status bar of empty documents has no background waking from suspension

### ISSUE THREAD

**Issue by jooadam** [vigna/ne#18]
Suspending and then waking with an empty document (even with one containing empty lines) open the status bar background is lost until text is inserted and repaints triggered.

This is present in both the latest release and the latest commit on master.

**Comment by utoddl** [comment]
This is addressed in the "suspend-anywhere" branch. I hope to merge that into "master" soon, after some more testing.

**Comment by utoddl** [comment]
"suspend-anywhere" branch work has been merge to "master", thereby fixing this issue. Closing.
