### ISSUE TITLE
Apostrophes are not highlighted with AutoMatchBracket on

### ISSUE THREAD

**Issue by jooadam** [vigna/ne#19]
The documentation of AutoMatchBracket states that apostrophes are paired, but they aren’t.

**Comment by utoddl** [comment]
Apostrophes are not paired with other apostrophes. They are paired with "backticks", m4 style. That is "`" to the left of "'" are paired. Just looking at a single apostrophe, there's no way to know whether it's on the left or right end of a pair.

**Comment by jooadam** [comment]
Sure, but that’s not what the documentation says: http://ne.di.unimi.it/docs/AutoMatchBracket.html

**Comment by utoddl** [comment]
That's a problem with the html generation. The in-app documentation is correct (^k help amb).

**Comment by utoddl** [comment]
Clearly we need to fix the issue with quotes in the docs. Re-opening this thread.

**Comment by utoddl** [comment]
Fixed and merged into "master". Closing issue.
