### ISSUE TITLE
Problematic Installation on CentOS

### ISSUE THREAD

**Issue by Cyan4973** [vigna/ne#2]
Tried to install `ne` on CentOS 6.6,
I believe I got the binary working, but it wasn't a smooth experience,
so I figure it would help to provide a feedback : 

`make install` failed as it required `makeinfo`.

```
makeinfo -D autohelp ne.texinfo
make[1]: makeinfo: Command not found
make[1]: *** [enums.h] Error 127
make[1]: Leaving directory
make: *** [build] Error 2
```

`makeinfo` can be found in the `texinfo` package `sudo yum install texinfo`, which is not too obvious.
Once installed, compilation proceeds smoothly, but installation fails (somewhat) as some doc files are missing :

```
cp: cannot stat `doc/ne.pdf': No such file or directory
cp: cannot stat `doc/html': No such file or directory
cp: cannot stat `doc/ne.txt': No such file or directory
make: *** [install] Error 1
```

In fact the binary is working, so I figure only the doc are missing.

There is a `makefile` into the `doc` directory, so tried to use it, in case it would generate the missing files. It triggers some new errors :

```
texi2dvi --clean ne.texinfo
make: texi2dvi: Command not found
make: *** [ne.dvi] Error 127
```

`texi2dvi` is supposed to be part of `texinfo`, but maybe not in the version of CentOS 6.

Well, hope it helps create a better installation experience.

**Comment by vigna** [comment]
> On 2 Jul 2015, at 03:29, Yann Collet <notifications@github.com> wrote:
> 
> Tried to install ne on CentOS 6.6,
> I believe I got the binary working, but it wasn't a smooth experience,
> so I figure it would help to provide a feedback :
> 
> make install failed as it required makeinfo.
> 
> makeinfo -D autohelp ne.texinfo
> make[1]: makeinfo: Command not found
> make[1]: *** [enums.h] Error 127
> make[1]: Leaving directory
> make: *** [build] Error 2
> 
> makeinfo can be found in the texinfo package sudo yum install texinfo, which is not too obvious.
> Once installed, compilation proceeds smoothly, but installation fails (somewhat) as some doc files are missing :
> 
> cp: cannot stat `doc/ne.pdf': No such file or directory
> cp: cannot stat `doc/html': No such file or directory
> cp: cannot stat `doc/ne.txt': No such file or directory
> make: *** [install] Error 1
> 
> In fact the binary is working, so I figure only the doc are missing.
> 
> There is a makefile into the doc directory, so tried to use it, in case it would generate the missing files. It triggers some new errors :
> 
> texi2dvi --clean ne.texinfo
> make: texi2dvi: Command not found
> make: *** [ne.dvi] Error 127
> 
> texi2dvi is supposed to be part of texinfo, but maybe not in the version of CentOS 6.
> 
> Well, hope it helps create a better installation experience.

You're right but... why didn't you use the RPMs?!

Ciao,

					seba

**Comment by Cyan4973** [comment]
Good point. Well, historically, I've had more difficulties with RPM installations than with sources.
As a consequence, I developed a "sources first" reflex.
Now, I don't even look at RPM if sources are present with a `make install` command.
I guess I also find sources are more instructive.

**Comment by vigna** [comment]
> On 2 Jul 2015, at 16:13, Yann Collet <notifications@github.com> wrote:
> 
> Good point. Well, historically, I've had more difficulties with RPM installations than with sources.
> As a consequence, I developed a "sources first" reflex.
> Now, I don't even look at RPM if sources are present with a make install command.
> I guess I also find sources are more instructive.

Previously, the install target included a "make build". Then we found difficult to pass the option to build needed by certain platforms, so I eliminated it (bad mistake). I'll try to find a way around.

For the dependencies: unfortunately there's no way to specify in a tar which are the dependencies (i.e., makeinfo and texi2dvi).

Ciao,

					seba

**Comment by Cyan4973** [comment]
I believe one "standard" way to check and warn for dependencies is a `./configure`.
That's the experience I had on installing some other software from sources.
For example, nano correctly detected and warned about the absence of ncurses from the ./configure.
I had similar experience with python, sanos, tilde, etc.
