### ISSUE TITLE
Existing files are overwritten without confirmation

### ISSUE THREAD

**Issue by jooadam** [vigna/ne#20]
Selecting an existing file when saving a document the existing file is overwritten without asking for confirmation. This makes it really easy to accidentally destroy files.

**Comment by vigna** [comment]
Well, that's a bit the UN*X way—if you mv a file over an existing file it won't ask for confirmation. Frankly, I never deleted a single file in this particular way.

**Comment by jooadam** [comment]
That’s a valid point of view, but if you prompt the user when an unsaved buffer is about to be closed, then I’d argue that you have already committed not to carry out destructive operations without confirmation.

I’ve been using Unixes for a decade now, and I cannot recall any instance of loosing work for lack of confirmation on the command line, but I had to restore from backup multiple times working with ne.

**Comment by utoddl** [comment]
I think there may be a way to extend the technique we use wrt file modification times to help in this case. But I want to be sure I understand the scenario you're describing @jooadam. Are you talking about saving and unnamed buffer, and/or SaveAs, with the name of an existing, unrelated file?

**Comment by jooadam** [comment]
@utoddl yep, that’s the scenario.

**Comment by utoddl** [comment]
It does warn now when SaveAs would overwrite an existing file. This is for buffers only, not streams, so SaveClip and SaveMacro are still "dangerous". Please test.

**Comment by jooadam** [comment]
Great!
