### ISSUE TITLE
Building Against netbsd-curses

### ISSUE THREAD

**Issue by githububub** [vigna/ne#24]
Build fails when building against <a href="https://github.com/sabotage-linux/netbsd-curses" target="_blank">netbsd-curses</a>...

>c99   -D_REGEX_LARGE_OFFSETS -D_GNU_SOURCE -DSTDC_HEADERS -Dinline=__inline__   -O3 -DNDEBUG   -D_FORTIFY_SOURCE=2  -c -o term.o term.c
term.c: In function ‘set_attr’:
term.c:360:30: error: too few arguments to function ‘tparm’
     const char * const buf = tparm(ne_set_foreground , joe2color(attr >> FG_SHIFT));
                              ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c:366:30: error: too few arguments to function ‘tparm’
     const char * const buf = tparm(ne_set_background , joe2color(attr >> BG_SHIFT));
                              ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c: In function ‘set_scroll_region’:
term.c:515:37: error: too few arguments to function ‘tparm’
  if (ne_change_scroll_region) buf = tparm (ne_change_scroll_region, start, stop);
                                     ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c:516:13: error: too few arguments to function ‘tparm’
  else buf = tparm (ne_set_window, start, stop, 0, ne_columns - 1);
             ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c: In function ‘insert_chars’:
term.c:775:28: error: too few arguments to function ‘tparm’
   const char * const buf = tparm (ne_parm_ich, width);
                            ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c: In function ‘delete_chars’:
term.c:865:28: error: too few arguments to function ‘tparm’
   const char * const buf = tparm(ne_parm_dch, n);
                            ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c: In function ‘do_multi_ins_del’:
term.c:880:28: error: too few arguments to function ‘tparm’
   const char * const buf = tparm(multi, n);
                            ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c: In function ‘calculate_costs’:
term.c:960:21: error: too few arguments to function ‘tparm’
   char *const buf = tparm(ne_repeat_char, ' ', 1);
                     ^~~~~
In file included from term.c:31:0:
/usr/include/term.h:1961:9: note: declared here
 char *  tparm(const char *, long, long, long, long, long,
         ^~~~~
term.c: In function ‘copy_caps’:
term.c:1026:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_column_address = column_address;
                    ^
term.c:1027:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_row_address = row_address;
                 ^
term.c:1029:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_address = cursor_address;
                    ^
term.c:1031:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_carriage_return = carriage_return;
                     ^
term.c:1033:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_home = cursor_home;
                 ^
term.c:1034:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_to_ll = cursor_to_ll;
                  ^
term.c:1036:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_right = cursor_right;
                  ^
term.c:1037:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_down = cursor_down;
                 ^
term.c:1038:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_left = cursor_left;
                 ^
term.c:1039:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_up = cursor_up;
               ^
term.c:1044:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_clr_eos = clr_eos;
             ^
term.c:1045:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_clear_screen = clear_screen;
                  ^
term.c:1047:10: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_bell = bell;
          ^
term.c:1048:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_flash_screen = flash_screen;
                  ^
term.c:1050:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_scroll_forward = scroll_forward;
                    ^
term.c:1051:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_scroll_reverse = scroll_reverse;
                    ^
term.c:1053:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_delete_mode = enter_delete_mode;
                       ^
term.c:1054:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_delete_mode = exit_delete_mode;
                      ^
term.c:1055:23: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_insert_mode = enter_insert_mode;
                       ^
term.c:1056:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_insert_mode = exit_insert_mode;
                      ^
term.c:1058:25: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_standout_mode = enter_standout_mode;
                         ^
term.c:1059:24: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_standout_mode = exit_standout_mode;
                        ^
term.c:1063:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_change_scroll_region = change_scroll_region;
                          ^
term.c:1065:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_insert_line = insert_line;
                 ^
term.c:1066:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_parm_insert_line = parm_insert_line;
                      ^
term.c:1067:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_delete_line = delete_line;
                 ^
term.c:1068:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_parm_delete_line = parm_delete_line;
                      ^
term.c:1070:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_insert_character = insert_character;
                      ^
term.c:1071:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_insert_padding = insert_padding;
                    ^
term.c:1072:14: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_parm_ich = parm_ich;
              ^
term.c:1074:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_delete_character = delete_character;
                      ^
term.c:1075:14: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_parm_dch = parm_dch;
              ^
term.c:1079:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_invisible = cursor_invisible;
                      ^
term.c:1080:19: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_cursor_normal = cursor_normal;
                   ^
term.c:1082:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_init_1string = init_1string;
                  ^
term.c:1083:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_init_2string = init_2string;
                  ^
term.c:1084:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_init_3string = init_3string;
                  ^
term.c:1085:19: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_ca_mode = enter_ca_mode;
                   ^
term.c:1086:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_ca_mode = exit_ca_mode;
                  ^
term.c:1088:25: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_attribute_mode = exit_attribute_mode;
                         ^
term.c:1089:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_alt_charset_mode = exit_alt_charset_mode;
                           ^
term.c:1091:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_repeat_char = repeat_char;
                 ^
term.c:1097:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_meta_on = meta_on;
             ^
term.c:1098:14: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_meta_off = meta_off;
              ^
term.c:1100:16: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_set_window = set_window;
                ^
term.c:1102:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_keypad_local = keypad_local;
                  ^
term.c:1103:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_keypad_xmit = keypad_xmit;
                 ^
term.c:1105:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_clr_eol = clr_eol;
             ^
term.c:1109:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   ne_set_background = set_a_background;
                     ^
term.c:1110:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   ne_set_foreground = set_a_foreground;
                     ^
term.c:1113:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   ne_set_background = set_background;
                     ^
term.c:1114:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   ne_set_foreground = set_foreground;
                     ^
term.c:1117:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_underline_mode = enter_underline_mode;
                          ^
term.c:1118:25: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_underline_mode = exit_underline_mode;
                         ^
term.c:1120:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_bold_mode = enter_bold_mode;
                     ^
term.c:1121:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_blink_mode = enter_blink_mode;
                      ^
term.c:1122:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_dim_mode = enter_dim_mode;
                    ^
term.c:1123:24: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_enter_reverse_mode = enter_reverse_mode;
                        ^
term.c:1124:25: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  ne_exit_attribute_mode = exit_attribute_mode;
                         ^
make[1]: *** [<builtin>: term.o] Error 1
make[1]: Leaving directory '/tmp/archives/ne/src/ne-3.0.1/src'
make: *** [makefile:16: build] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Perhaps you can provide an ne.info to `tic -s` into a CDB terminfo file?

**Comment by vigna** [comment]
> On 13 Nov 2016, at 02:41, GitHububub <notifications@github.com> wrote:
> 
> Build fails when building against netbsd-curses...
> 
> c99 -D_REGEX_LARGE_OFFSETS -D_GNU_SOURCE -DSTDC_HEADERS -Dinline=inline -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -c -o term.o term.c
> term.c: In function ‘set_attr’:
> term.c:360:30: error: too few arguments to function ‘tparm’
> const char * const buf = tparm(ne_set_foreground , joe2color(attr >> FG_SHIFT));

Apparently a problem with the tparm declaration in the library, or with the compiler. Given that the distribution is "radical and experimental" I would look there for the problem...

Ciao,

					seba
