### ISSUE TITLE
Backspace does not work on Mac

### ISSUE THREAD

**Issue by SurfaceThought** [vigna/ne#25]
Hello there,

I love ne and use it as my text editor of choice on my home linux computer. For work, however, I must use a Mac. For whatever reason, despite it being interpreted correctly in every other application, when I press backspace while in ne it interprets it as a delete. The backspace even works correctly when I ssh into the linux server with the same computer, running the same version of ne compiled from the same source. 

Anyone run into this problem before? Any advice would be greatly appreciated.

Thanks!

Edit: I previously searched the issues for "mac" and didn't see anything relevant but I know see that issue 10 *may* be relevant. Looking through the resources provided currently.

**Comment by vigna** [comment]
Usually it's just the terminal you're using that's wrong. Can you post the output of infocmp ? Have a look also at my mini-HOWTO on Backspace and Delete.

**Comment by SurfaceThought** [comment]
Hey there!

Indeed, I did take a look at that HOWTO... and I am still not sure I understand where the issue can be coming from.

The backspace works correctly in every other application, both in iterm2 as well as apples default terminal app. In addition, it even works on both terminals when I am ssh'd into the red hat server. It literally just appears to be ne running locally on the mac, on both iterm2 and the default terminal app.

infocmp output: https://gist.github.com/SurfaceThought/b4174a18183b29c271701aaee9e34250

In addition, the output of the ascii one liner from the HOWTO:

Backspace:

10 0x0A

Delete:

27 0x1B
91 0x5B
51 0x33
126 0x7E
10 0x0A

Thanks for the help!

**Comment by vigna** [comment]
In the iTerm2 profile, do you have "Delete key sends ^H" set?

**Comment by SurfaceThought** [comment]
No, that box is unchecked.

**Comment by SurfaceThought** [comment]
Well, how about that, checking the box fixed the issue. Thank you!

**Comment by carlsmith** [comment]
I had the same issue, but with Terminal. Adding this line to my `.keys` file fixed it:

```
KEY 7f Backspace
```

**Comment by MarcusE1W** [comment]
@carlsmith tips solved it for me on Archlinux with Termite teminal too :-)

**Comment by QtRoS** [comment]
One more discussion which helped me too: https://gist.github.com/andscoop/874ff042a28ca5aaa06426a58aacaf83
