### ISSUE TITLE
IPython Syntax Highlighting

### ISSUE THREAD

**Issue by carlsmith** [vigna/ne#27]
Firstly, thanks to everyone who works on `ne`. A nice editor for Unix was definitely needed, and `ne` is really well thought out.

I'm trying to create a syntax recogniser for IPython files (based off the Python one). IPython uses Python syntax, with a few extra features:

1. If the first visible character on a line is `!`, the rest of the line is a system command (that will be passed to the underlying shell).
2. If the first visible character on a line is `%`, the rest of the line is a 'magic command', a user-defined shell command. For highlighting purposes, they are indistinct from Case 1.
3. IPython also adds a new assignment statement. The grammar is `<name> =! <command...>`. The `<name>` token is a normal Python name, and `<command...>` is every token to the right of `=!`, till the end of the line.

It would be nice if Case 1, Case 2 and the `<command...>` part of Case 3 were highlighted as 'shell syntax', but even just making them all one colour, like a comment, works pretty well in practice.

I tried copying the syntax definition for `comment`, renaming it `command` and using `"!%"` instead of `#`. This works to an extent. All three cases are all highlighted correctly. The problem, as you probably guessed, is that it breaks highlighting for the regular Python `%` and `!=` operators (modulo, and not equal). Those operators also now cause the rest of the line to be highlighted as a `command`.

**Comment by utoddl** [comment]
@carlsmith could you post a gist of your .jsf? These things are incredibly hard to describe. To paraphrase: talking about .jsf is like dancing about architecture.

**Comment by carlsmith** [comment]
No problem @utoddl. [The gist is online here][1]. I added a comment there that points out what edits have been made to the original file.

[1]: https://gist.github.com/carlsmith/1ed7ef88b7125351bc5ac6d52fdbfc87

Thank you for looking into this.

If we can get IPython syntax highlighting working properly, I'll post something to the IPython mailing list, sharing my configuration, and explaining and plugging `ne` a bit.

**Comment by carlsmith** [comment]
My attempt was to just highlight the commands magenta. Ideally they should be highlighted using `sh.jsf`.

**Comment by utoddl** [comment]
Here's me, eating my words. Remember what I said about talking about .jsf is like dancing about architecture? Time to dance. :) I sort of see what you're shooting for, but I'd like to suggest a less invasive approach. Let's go back to the python.jsf as distributed with ne and start fresh from there.

Notice that all states with the exception of :idle of course (and ":comment", which is probably a mistake) which transition to "idle" do so with a noeat. This is very important, as it means that pretty much every "\n" is going to send you back to "idle".

From my reading of the iPython pages, the only times we deviate from normal Python syntax is at the beginning of lines or immediately after an equals sign, give or take some white space. So let's wedge this in between the existing colour definitions and "idle":

    =IpTag          inverse green
    =IpString       inverse yellow

    :maybe_ip Idle
            *               idle            noeat
            " \t"           maybe_ip
            "!%"            ip_tag          noeat
    :ip_tag IpTag
            *               ip_string       noeat
            "!%"            ip_tag
    :ip_string IpString
            *               ip_string
            "\n"            maybe_ip

This defines two new colors: one for the tags and one for the strings. It also makes your default/first state "maybe_ip" using the Idle colour. It skips over spaces looking for either "!" or "%" without consuming them. Anything else sends us to "idle", so we don't mess up the rest of the Python syntax. "ip_tag" eats the bang and percent signs, then transitions to "ip_string", which eats everything to the end of line.

We still need "idle" to deal with possible iPython magic after an equals sign or new lines. So let's add this transition to "idle":

      "=\n"           maybe_ip

It eats, so the equal sign gets the Idle colour, but we go looking for iPython magic. If we don't find it, "maybe_ip" noeats and goes right back to Idle, so again, we don't break any of the Python syntax.

The only other thing I'm seeing is the missing noeat on "comment"'s transition on newline, so add that:

      "\n"            idle            noeat

And I think we're done. You'll probably want to tweak the colors, and you may find some circumstances that I didn't spot. But I think we're closer to what you wanted without breaking the existing Python bits. Give it a try and let us know what you think.

**Comment by carlsmith** [comment]
Thank you for this @utoddl. It's really kind of you to take the time, and your help is much appreciated mate. I'll check the new code out this evening, and let you know how it goes. I really just wanted to say thank you.

**Comment by carlsmith** [comment]
I just got a chance to try it out. It works perfectly. Thank you @utoddl.

I was already a `ne` fan. IPython support is a really nice extra, and your willingness to help your users like you have here is really appreciated. I'm totally comfortable promoting `ne`, and will be writing something about it for the IPython community really soon.

Awesome work. Thanks again man.
