### ISSUE TITLE
Python syntax definition is missing the `nonlocal` keyword

### ISSUE THREAD

**Issue by carlsmith** [vigna/ne#28]
Python 3 added a `nonlocal` keyword (it does a similar thing to `global`). It just needs adding to `python.jsf`.

I also quickly checked that the file includes the rest of Python's keywords; it does.

**Comment by utoddl** [comment]
Thanks, @carlsmith . I've added that to the defprefs branch and it will get merged to master soon I expect.

**Comment by utoddl** [comment]
Merged into master branch. Closing this issue. Thanks again.
