### ISSUE TITLE
While building, receiving a c99: command not found error.

### ISSUE THREAD

**Issue by tristan957** [vigna/ne#31]
Where is c99 being used? I would like to replace it with gcc -std=c99 instead?

**Comment by utoddl** [comment]
On my system, c99 is a script that does exactly that: call gcc with -std=c99 and all other parameters passed unchanged. Behold:
````
$ cat /usr/bin/c99
#!/bin/sh
fl="-std=c99"
for opt; do
  case "$opt" in
    -std=c99|-std=iso9899:1999) fl="";;
    -std=*) echo "`basename $0` called with non ISO C99 option $opt" >&2
	    exit 1;;
  esac
done
exec gcc $fl ${1+"$@"}
````

**Comment by tristan957** [comment]
Yea I think I got it figured out I just need to use sed to replace c99 with the gcc version. Thanks for your help.

**Comment by tristan957** [comment]
@utoddl I got past the previous error and am getting this

`cp -pr doc/ne.pdf doc/html doc/ne.txt doc/default.* README.md COPYING NEWS CHANGES /home/build/YPKG/root/ne/install/usr/local/share/doc/ne
cp: cannot stat 'doc/ne.pdf': No such file or directory
cp: cannot stat 'doc/html': No such file or directory
cp: cannot stat 'doc/ne.txt': No such file or directory`

I believe it has to do with the /docs/makefile. Any idea what I need to do to fix this?

**Comment by utoddl** [comment]
This should do it:
````
cd doc
make
````
You may find you don't have `texinfo` and/or some other required packages (`ncurses-devel`, `make`, `bash`, `perl`, `texinfo`, `sed`). I'm curious what system you're working on that has gcc but not c99? Also if you run into additional issues we'd like to know about that. Good luck, and thanks for trying `ne`.
