### ISSUE TITLE
RepeatLast should allow to specify whether to do Find or Replace (was Crtl-G default behaviour)

### ISSUE THREAD

**Issue by pepa65** [vigna/ne#33]
I get bitten by this every once in a while, that Ctrl-G which I want to use for Find Again, after doing a Replace it defaults to Replace Again, which can be quite destructive. If it would default back to the thing you were finding, I could always easily start the replace again with Ctrl-R and arrow-up to the desired term.

It's just that in case of a replace session, some things you say NO to, because you need to check something. Often you want to find the same thing, but you usually don't want to continue replacing straight away again.

Hope this makes sense. Because replace has it's own 'session', I never use Ctrl-G to replace again, in my muscle memory it means: Find Again (I use find way more often than replace).

**Comment by pepa65** [comment]
By the way, very excited about the coming release!!

**Comment by vigna** [comment]
I see, but there's a logic: CTRL-G is "Repeat Last". If you search and replaced a single item, but you want to replace some more, just hit CTRL-G. I think in fact people is quite used to that by now...

**Comment by pepa65** [comment]
But when you enter replace, you enter into a whole different level of UI. When you exit that, it is strange (and destructive!) to have Ctrl-G to do a replace outside of the replace UI.

Maybe could you add a Find Last command?? Then I'll change my Ctrl-G locally. :-)

**Comment by pepa65** [comment]
Would you prefer if I open a new Issue on the request for a Find Last command??

**Comment by utoddl** [comment]
If you've been doing Replace, and you want go back to doing Find, why not just do "^F<Enter>"? The Find prompt defaults to the prior Find string. There's some value in keeping the number of commands in the "find and replace" suite small. The bar for adding new commands needs to be pretty high, and I'm not sure that FindLast would meet that test when Find basically does it already.

**Comment by pepa65** [comment]
I don't like for a replace to happen when I want to repeat a find. Maybe I can just redefine Ctrl-G as Ctrl-F <Enter>?

If you want to keep the number of commands small, I think a Repeat Last Find would be more useful than a Repeat Last Find/Replace.

Or, can I request a configuration option to change Repeat Last to not include Replace??

**Comment by utoddl** [comment]
There are too many config options/flags already, and adding new commands is a very large hammer for such a small (thumb)nail. But I think your original idea is correct -- that it should be as easy to do a RepeatLastFind or RepeatLastReplace as it is to do a RepeatLast. RepeatLast is certainly useful, but it is also quirky enough to constitute a barrier-to-entry for new users.

After having thought about it a while, I think the right answer is to add an optional parameter to RepeatLast, which would be [F|Find|R|Replace]. The default action would be as it is now -- whichever was done most recently -- but you could map a key to "RepeatLast Find" to get the behaviour you expect.  I'll take a look to be sure, but this should take a minimal amount of code, doesn't break existing behaviour, and fills a reasonable expectation. (Also, not easily done with macros; I tried. Ugh.)

**Comment by pepa65** [comment]
Thank you for your thoughtful consideration! I will surely use this a lot.

**Comment by utoddl** [comment]
@pepa65 There is now a "repeatlast" branch. Please check it out and see what you think.

**Comment by pepa65** [comment]
Super! Just works (tm)..! Thanks a lot.

**Comment by pepa65** [comment]
Thank you for your thoughtful consideration! I will surely use this a lot.

**Comment by pepa65** [comment]
I don't know what's wrong with my system suddenly, no matter which branch or version I build, I can make it segfault by editing an existing file, and then: Enter Up 's'

**Comment by utoddl** [comment]
Which branch did you pull from? I think we have recently committed some bad code somewhere, and we're trying to sort things out right now. So sorry.

**Comment by vigna** [comment]
Sorry guys this must be me. I'm doing experiments in the master branch, which is of course criminal...

**Comment by pepa65** [comment]
Any branch -- at least I my (file?)system is not getting hosed (or I going crazy or incompetent...)!

**Comment by pepa65** [comment]
Does it not segfault at your end??
`ne README.md` then Enter Up Space

**Comment by utoddl** [comment]
No, it doesn't. Make sure you're starting from a really clean tree. There were some changes in cc options that might be hurting you if you have leftover .o files, which a `git checkout` wouldn't fix:
```
make clean
cd doc && make clean
cd ../src && make clean
cd ..```

**Comment by pepa65** [comment]
That didn't do the trick... Now I've done `cd ..; rm -rf ne; git clone https://github.com/vigna/ne; cd ne; make build; sudo make install; src/ne README.md` and then get a segfault after Enter Up Space.

**Comment by vigna** [comment]
Fixed!

**Comment by pepa65** [comment]
Master branch is good here now. The repeatlast branch still segfaults the same way.

**Comment by pepa65** [comment]
The repeatlast branch is now also working!
