### ISSUE TITLE
make NE_DEBUG=1 

### ISSUE THREAD

**Issue by pepa65** [vigna/ne#34]
I pulled the fresh sources from here just now, build it with make NE_DEBUG=1 and started editing a document, and this happened:
```
ne: buffer.c:1285: load_fd_in_buffer: Assertion `(cp)->last_used == (cp)->size - 1 || (cp)->pool[(cp)->last_used + 1] == 0' failed.
Aborted (core dumped)
```
A normal `make` gives me a working binary.

**Comment by vigna** [comment]
Can you try the fast-load branch? I think it's fixed there.

**Comment by vigna** [comment]
I take it as a "yes" :)

**Comment by pepa65** [comment]
Yes, fast-load branch works!
