### ISSUE TITLE
[Syntax Highlighting] Recognise ES6 Splats

### ISSUE THREAD

**Issue by carlsmith** [vigna/ne#39]
In JavaScript ES6, they added a prefix operator (`...`) for gathering arguments into an array and for spreading an array into arguments.

1) It can appear before a param (in function/generator statements/expressions), and is used to gather arguments into an array:

    ``` javascript
    let f = function (...args) { console.log(args) };
    ```

2) It can also appear before an argument to an invocation. The argument (which must be an expression that evaluates to a sequence) is expanded into individual arguments:

    ``` javascript
    f(...[1, 2, 3]);
    ```
The JavaScript highlighter currently treats both cases as syntax errors.

**Comment by utoddl** [comment]
`typescript` is a superset of `JavaScript`, or was until recently. Somewhere along the way [JOE](https://sourceforge.net/projects/joe-editor/) added a `typescript.jsf` which simply invokes `js.js(typescript)`. That is, it just runs JOE's updated js.jsf with a parameter to tell it to use the `typescript` extensions which, after playing with it a bit, appears to properly support this new _spread_ operator. (Nothing in this paragraph was known to me an hour ago.)

I have no idea how much ES6 has diverged from `typescript`, but it's possible you could use those files from JOE with no or minor tweaking to get the effect you're after. At the very least, you could remove the `.ifdef typescript`...`.endif` from around the parts that deal with ellipsis in JOE's js.jsf.

Tweaking .jsf files is tricky, and some of these languages just won't hold still. You clearly are more familiar with JavaScript than I am. If you can follow what I outlined above and have any success, we'd very much like to hear about it. I'm a little hesitant to pull those .jsf files into ne without having at least one real JavaScript user having a go with them.

Besides JOE, there's another project on github owned by @cmur2 ([cmur2/joe-syntax](https://github.com/cmur2/joe-syntax)) which we work with occasionally for .jsf issues. Unfortunately that set of .jsf files also does not yet have the `typescript` extensions or the new _spread_ operator for JavaScript. Now that it's on our radar maybe that can change soon.
