### ISSUE TITLE
Line does not update properly with syntax highlighting

### ISSUE THREAD

**Issue by thabubble** [vigna/ne#41]
I built ne from the 3.1.1 tarball and the cloned git repo. Everything works except the text does not update correctly when I have syntax highlighting enabled. 
It works fine when I append text to the line, it does not work when I edit the line itself; the characters are not updated until I manually redraw the screen or enough characters are added(the whole line is not updated). When I make a new line the content after the cursor is pushed to the new line and displayed correctly.

I've tried compiling with -std=c99 and without -O3

gcc version 6.2.0

**Comment by thabubble** [comment]
This is observed in aterm and urxvt but not in Linux VT

**Comment by thabubble** [comment]
Changing $TERM to any other in my terminfo except for vt1* and rxvt* makes it work. The problem still persists if they are used, even in ansi mode.

**Comment by vigna** [comment]
That's really weird—in ANSI mode we do _not_ look at the terminal, in any way.

**Comment by vigna** [comment]
I've been able to replicate the problem. It's exclusively a database problem—it happens even on xterm if I set TERM=rxvt.
