### ISSUE TITLE
Allow scripting

### ISSUE THREAD

**Issue by italomaia** [vigna/ne#42]
It would be very nice to be able to run code validation in open files, like linters.

**Comment by vigna** [comment]
Well you can do it with the THROUGH command.

**Comment by italomaia** [comment]
@vigna where can I find docs for this command?

**Comment by vigna** [comment]
RTFM? 😂

**Comment by italomaia** [comment]
Found it http://ne.di.unimi.it/docs/Through.html#index-Through
I believe "through" alone would not do, as it would need to be able to show a message of sorts to the user. Maybe in a panel of sorts.

**Comment by utoddl** [comment]
You're not wrong, but there are possibilities. Look at the "aspell" macro to get some ideas. It's not likely to happen that something like this gets integrated into ne, but the technique of using Through as in the aspell macro may make it possible to use external tools in conjunction with ne.
