### ISSUE TITLE
compile just the executable

### ISSUE THREAD

**Issue by kroggen** [vigna/ne#47]
Hi!

First of all, thank you for this editor! It is my preferred editor on Linux and Mac.

How to compile just the executable without texinfo?

I saw that it needs it to create the `enum.h` file

**Comment by utoddl** [comment]
It creates `enums.h`, `names.c`, `names.h`, `hash.c`, `hash.h`, `help.c`, `help.h`, and `ext.c` from the documentation, specifically from the output of texinfo. They are not in the git repo, but they are included in the tarball available at
http://ne.di.unimi.it/ (which I see is ne-3.1.1; hmm), or temporarily from
https://www.unc.edu/~utoddl/ne-3.2.0.tar.gz (I just put that up, but that whole web space is going away later this year.)
If you un-tar those files and the timestamps are such that it still wants to build the texinfo docs, just
`touch enums.h names.c names.h hash.c hash.h help.c help.h ext.c`
in the `src` directory and you should be good to `make` in the `src` directory. I normally do
`make OPTS='-DALTPAGING -std=c99' NE_GLOBAL_DIR=/usr/share/ne PREFIX=/usr "$@"`
in `src` when I'm working on the code. See the caveats on "ALTPAGING" in `src/makefile` though.

**Comment by kroggen** [comment]
Wow, It worked!

Thank you so much!
