### ISSUE TITLE
Ran "make install", failed with issue "cp: src/ne: No such file or directory"

### ISSUE THREAD

**Issue by AbhishekSaha** [vigna/ne#5]
I downloaded the zip file for this project, unzipped, and ran make install. The installation failed, here's what is in my terminal. I am running OS X Yosemite with XCode command line tools installed. 

    $ make install
    mkdir -p /usr/local/bin
    mkdir -p /usr/local/share/ne/syntax
    mkdir -p /usr/local/share/ne/macros
    mkdir -p /usr/local/share/man/man1
    mkdir -p /usr/local/share/doc/ne
    mkdir -p /usr/local/share/info
    cp -pf src/ne /usr/local/bin
    cp: src/ne: No such file or directory
    make: *** [install] Error 1

**Comment by vigna** [comment]
Just

make
make install

**Comment by AbhishekSaha** [comment]
Got these errors after doing that:

cp: doc/ne.pdf: No such file or directory
cp: doc/html: No such file or directory
cp: doc/ne.txt: No such file or directory
make: *** [install] Error 1

**Comment by vigna** [comment]
Did you

1) untar a fresh copy
2) cd in
3) "make"
4) "make install"

?

I have Yosemite and I can't reproduce.

**Comment by AbhishekSaha** [comment]
Thanks I got it to work

**Comment by jooadam** [comment]
@vigna One must also issue `make docs` before install.
