### ISSUE TITLE
toml syntax file in place of ini jsf?

### ISSUE THREAD

**Issue by uvtc** [vigna/ne#66]
I see that the very popular [toml](https://github.com/toml-lang/toml) config file format is very similar to the ini file format. My understanding is that the toml format is much more rigorously specified than the ini format.

Would it make sense to change the ini.jsf syntax file into toml.jsf, and have that one loaded not only when .toml files are opened, but also when .ini files are opened?

**Comment by uvtc** [comment]
Possibly related:

https://github.com/cmur2/joe-syntax/issues/26

**Comment by utoddl** [comment]
toml is really a different beast. f60f1014ab637b287e862fa00a473fe275077437 adds a real `toml.jsf`.

**Comment by uvtc** [comment]
Great!
