### ISSUE TITLE
NE is buggy on under termux - backspace key

### ISSUE THREAD

**Issue by italomaia** [vigna/ne#67]
Basically, backspace key doesn't work properly. More info below:

https://github.com/termux/termux-packages/issues/1085

**Comment by craigbarnes** [comment]
This seems like a duplicate of issue #48.

**Comment by Salamandar** [comment]
Same here, but not on Termux but Archlinux.

**Comment by vigna** [comment]
On Mac OS X any terminal application will let you have the <- key send a ^H (which is something it should do in the first place).
