### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by tapir** [vigna/ne#7]
I know "ne" is capable of doing colors because of the screenshot on your main page but I can't get it to work on any platform. So far I've tried cygwin, gnome-terminal and rxvt-unicode.

Here is a screenshot taken from Windows 7 for a lua sample code: http://i.imgur.com/f1iNI5C.png

**Comment by tapir** [comment]
After some tests I've concluded that it's the lua syntax definition's fault. I'll try to improve it.

**Comment by vigna** [comment]
Did you try to edit other kind of files? You should also try with more recent joe syntax files (we use joe's syntax code).

**Comment by tapir** [comment]
When I tried a C file I've noticed that colors are OK. I think it's the lua.jsf file that is not so good. I'll try newer ones from joe or modify it myself

**Comment by tapir** [comment]
Tried with the latest lua.jsf from Joe 4.1 and this is the result: http://i.imgur.com/RtJlUzw.png

I hardly call this syntax highlighting :D I will have to figure this jsf thing.

**Comment by tapir** [comment]
Closing since this is not a ne issue.
