### ISSUE TITLE
NEWS and CHANGES out of date

### ISSUE THREAD

**Issue by uvtc** [vigna/ne#72]
I see on [the ne site](http://ne.di.unimi.it/) that ne-3.3.0 is available, but the NEWS and CHANGES files appear to be out of date.

**Comment by vigna** [comment]
Oops we forgot to update the dates. Done!

**Comment by uvtc** [comment]
Sorry, I wasn't clear. I wasn't seeing the changes here on github as well (I see you've updated the site). Maybe you just haven't sync'd up with github.

**Comment by vigna** [comment]
Yep, I forgot to push. Thanks again.
