### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by carlyounger** [vigna/ne#76]
Will there be a build targeting macOS on ARM? `ne` is one of the programs I'm really missing. Thanks.

**Comment by vigna** [comment]
Can you do a PR?

**Comment by carlyounger** [comment]
I'm not sure, but can certainly try. I'll let you know how I get on.

**Comment by carlyounger** [comment]
Sorry I haven't got back to you yet. I just bought a new machine, reformatted my old one, gave it away, and now I don't have anything set up.

**Comment by vigna** [comment]
Any luck?

**Comment by 7ombie** [comment]
Completely forgot. Sorry. I'll look into it this evening.

**Comment by kroggen** [comment]
I was able to build it on an M1. There were some warnings. The logs are [here](https://gist.github.com/kroggen/46b358addaf5d47b101b9c069e60db81)

I don't know how to create a "build", but I uploaded the entire `ne` folder [here](http://litesync.io/ne-build-on-m1.tar.gz)

**Comment by vigna** [comment]
In theory if you do a "make macosx" you should get an ne-3.3.1.dmg which installs on Apple Silicon. Would you mind to try?

**Comment by vigna** [comment]
Note that at this point both MacPorts and HomeBrew have ports of ne, so if you have those installed you can just get their version.

**Comment by kroggen** [comment]
I installed `texinfo` using HomeBrew but it still gives this: (when running `make macosx`)

```
pdftex ne.texinfo
make[1]: pdftex: No such file or directory
```

But the package is indeed already available on HomeBrew (I tested and it worked). Maybe this can be closed

**Comment by vigna** [comment]
Oh I see. Apparently texlive is part of the dependencies of texinfo on Linux but not on HomeBrew. 

If you have the patience of installing texlive and try again, that would give us an installable DMG. But I must admit that it is unlikely that someone uses ne and does not have HomeBrew or MacPorts installed.
