### ISSUE TITLE
Compile on Alpine Linux

### ISSUE THREAD

**Issue by kroggen** [vigna/ne#78]
Hello!

I was not able to compile `ne` on Alpine Linux

It appears to be related with the use of busybox

```
localhost:~/ne# make
( cd doc; make )
make[1]: Entering directory '/root/ne/doc'
( cd .. ; make version )
make[2]: Entering directory '/root/ne'
./version.pl VERSION=3.3.1
/usr/bin/env: unrecognized option: S
BusyBox v1.32.1 () multi-call binary.

Usage: env [-iu] [-] [name=value]... [PROG ARGS]

Print the current environment or run PROG after setting up
the specified environment

	-, -i	Start with an empty environment
	-u	Remove variable from the environment
make[2]: *** [makefile:34: version] Error 1
make[2]: Leaving directory '/root/ne'
make[1]: *** [makefile:18: version.texinfo] Error 2
make[1]: Leaving directory '/root/ne/doc'
make: *** [makefile:28: docs] Error 2
```

**Comment by vigna** [comment]
Sorry, I lost this somehow.

I think we do not need the `-w` option, which means that wherever you find 

    #!/usr/bin/env -S perl -w

you should be able to replace

    #!/usr/bin/env perl

without any problem. @utoddl, am I right? We might do the replacement in the next version.

**Comment by utoddl** [comment]
You are right. In fact, some `env`s don't support `-S`, so this ends up not working everywhere anyway.
Good intentions, but a flawed implementation.

**Comment by vigna** [comment]
I just committed 577c7ac41fcb6, which fixes the problem. Let us know if it works for you...

**Comment by kroggen** [comment]
OK, now it worked (after installing `texinfo` and `ncurses-dev`)

Thank you!
