### ISSUE TITLE
Feature request: Search upwards

### ISSUE THREAD

**Issue by kroggen** [vigna/ne#79]
Hello!

It is very common to me the requirement to make a search from where the cursor is located upwards.

What about the interface to be like this:

`Ctrl+F` to open the Search bar, then `Shitf+Enter` to search up.

Then `Ctrl+G` will search for the next occurrence, remembering the direction.

**Comment by vigna** [comment]
Why don't you bind SearchBack to Shift+Enter (given that you have a sequence for that)? You can invoke it before Ctrl+F, and the status bar will tell you whether you're going forward or backward (it's the third letter—a 'b' will appear if you're searching back).

**Comment by kroggen** [comment]
Oh, I did not know that it already supports it.

How do we make a search up? There is no bound keys for that feature?

I was not able to find on the [default.keys](https://github.com/vigna/ne/blob/master/doc/default.keys)

**Comment by vigna** [comment]
If you read my comment, it says to bind SearchBack to a key. You can execute it as a command anyway.

**Comment by utoddl** [comment]
`SearchBack` is not in the menus either, which surprised me a little bit. I rarely use it, but when I do I just set / reset it from the command prompt:
```
^k sb <Enter>
```
Re: "given that you have a sequence for that" -- he meant that would work if and only if your terminal sends some character sequence for Shift+Enter that ne can distinguish from plain old Enter. (Mine doesn't.) You can experiment with some key combinations to see what `ne` sees for them with the `KeyCode` command. Bring up the command prompt (`^k`) then hit the key or key combination you want to check -- `Shift+Enter` for example. For my terminal, `ne` sees exactly the same thing it sees for a plain Enter. Likewise for Ctrl+Enter and Ctrl+Shift+Enter.
If you want to map a key or key combination to `SB` (`SearchBack`), you'll probably have to pick something besides the Enter key.

**Comment by kroggen** [comment]
Oh, I never "executed" nor "bound" anything on ne before, this is why I was a bit lost. But now I got it.

Thank you so much for your help!

PS: I agree, it could be in a menu
