### ISSUE TITLE
2 nice features

### ISSUE THREAD

**Issue by nereusx** [vigna/ne#8]
### PATCH 1

This patch enables to use bookmarks with the same way as in BRIEF.
It just adds the parameter '?' to the GotoBookmark buildin command.
This parameter just using the request_number() to get the number of the bookmark to go.

src/actions.c:
line ~282
``` ...
    case SETBOOKMARK_A:
    case GOTOBOOKMARK_A:
        {
            bool relative = false;
            /* *p can be  "", "-", "0".."9", "+1","-1", for which, respectively, */
            /*  c becomes  0, AB,  0 .. 9,  next,prev. Anything else is out of range. */
            if (p) {

                /* patch starts here... */
                /*  now c can be '?'; this asks user for the bookmark number 
                *  (BRIEF compatibility)
                */
                if ( p[0] == '?' ) {
                    c = request_number("Mark", 1);
                    if ( c < 0 || c > 9 )
                        return NUMERIC_ERROR(c);
                    }
                else /* patch ends here... */

                if ((p[0]=='+' || p[0]=='-') && p[1]=='1') {
      ...
```
Now, in the ~/.ne/.keys, we can use the '?' parameter to ask the bookmark number...
Nice BRIEF's bookmarks :)

```
# alt+num
KEY 1B1 SetBookmark 1
KEY 1B2 SetBookmark 2
KEY 1B3 SetBookmark 3
KEY 1B4 SetBookmark 4
KEY 1B5 SetBookmark 5
KEY 1B6 SetBookmark 6
KEY 1B7 SetBookmark 7
KEY 1B8 SetBookmark 8
KEY 1B9 SetBookmark 9
KEY 1B0 SetBookmark 0
# alt+j digit [enter]
KEY 1EA GotoBookMark ?
```

### PATCH 2

This patch uses the current text line if there is no selected text (no mark) for
the copy/cut commands. This is a nice feature that exists at BRIEF and NANO text editors.

src/actions.c
line ~1344
```                ...
    case COPY_A:

        /* patch begins here */
        if ( b->marking == 0 ) { 
            /* there is no mark, use the whole line */
            move_to_sol(b);
            b->mark_is_vertical = 0;
            b->block_start_line = b->cur_line;
            b->block_start_pos = b->cur_pos;
            b->marking = 1;
            if (line_down(b) != OK )
                move_to_eol(b);
            }
        /* patch ends here ... */

        if (!(error = print_error((b->mark_is_vertical ? copy_vert_to_clip : copy_to_clip)(b, c < 0 ? b->o
                ...
```
Thank you for your nice and good written code.

**Comment by utoddl** [comment]
"Patch 1" -- adding a "?" parameter to SetBookmark and GotoBookmark -- has been implemented, though not exactly as described above. The prompt accepts any valid bookmark designations: 0 through 9, "+1", "-1", "-", and for SetBookmark, "*". The prompt also indicates which numbered bookmarks are set.

"Patch 2" seems very similar to DeleteLine/UndeleteLine. It has the unpleasant side effect of altering the semantics of the cut/copy/paste suite, adding a one-off surprising special case of unexpected behaviour. I'm not saying this wouldn't be useful in some circumstances, but complicating behaviours raise the barriers for newcomers. Also, you could easily implement the behaviour you want with a macro bound to a key. No need to break Copy for this.

(Apart from that, as implemented above, this also means that in some cases a Copy could change your current position, which is a no-no. Easy enough to fix, but one more example of why "obvious easy features" are not always accepted.)

**Comment by nereusx** [comment]
Thanks Todd

About the line-copy/cut I found it so crusial so I ll keep a different copy of ne patched with this, off course because I was long term BRIEF user of the middle 80s.

But why not a flag in the ~/.ne/.defautl#ap ?
After all it is matter of two other popular editors.

Another solution would be from script but I cant get info if there is a 'mark' on.

**Comment by pepa65** [comment]
The nice thing about DeleteLine/UndeleteLine is that it keeps a single line in a separate buffer. The Paste buffer is untouched. (I don't think many users would realize this -- which then is unexpected...)

The downside is, it does take up an extra key combo. I do like that with the BRIEF/nano behaviour one can cut a number of lines in succession and then paste them in one go.
It doesn't really change the semantics, because the semantic is undefined when nothing is selected (or you could say: nothing happens).

Is it possible in a macro to check if the Paste-buffer is empty when Cut is invoked, so that the desired behaviour can be emulated??

I would be in favour of adding a setting in default#ap as the easiest and cleanest way to implement this.

**Comment by vigna** [comment]
Well, we are really against adding options that are not absolutely necessary (they are already far too many). Presently there's no way to implement that with a macro, unfortunately.
