### ISSUE TITLE
Matching braces

### ISSUE THREAD

**Issue by kroggen** [vigna/ne#80]
The editor is not matching braces when there is one in a comment.

To reproduce, type in the command line:

```
ne test.c
```

Then paste this code:

```c
  if (xx) {
    if (yy) {

    } else {  // a comment here {

    }
  }
```

Move the cursor to one of the last 2 curly braces.

Not a big problem, though.

**Comment by vigna** [comment]
Yes, even if you have a brace inside a string, etc. The matching algorithm is very basic and content-agnostic.
