### ISSUE TITLE
Error: File doesn't exist

### ISSUE THREAD

**Issue by kroggen** [vigna/ne#85]
To replicate, we need a folder structure like this:

```
+ parent
  |- test
  |- test-longer
```

Then run:

```
cd test-longer
ne
```

Then select File > Open New, go up a folder (..), select the `test` folder (shorter name), select any file, and it gives:

`File doesn't exist.`

The error happens when the name of one folder (the shorter) is the beginning of the name of the other folder (larger name). Another example:

```
+ parent
  |- abc
  |- abcde
```

Nice Editor version 3.3.1

**Comment by utoddl** [comment]
Took a while to figure out what you meant.
```
+ parent/
  |- test/
  |  + sample.txt
  |- test-longer/
```
So starting ne in the `test-longer` directory, the file selector doesn't allow you to open `test/sample.txt`.

**Comment by utoddl** [comment]
This is now fixed in the master branch.
Thanks, @kroggen, for reporting this issue!

**Comment by kroggen** [comment]
Wow, so fast!

Thank you!
