### ISSUE TITLE
Autocomplete with empty prefix causes ne to hang (macos)

### ISSUE THREAD

**Issue by soveran** [vigna/ne#88]
When trying to autocomplete with an empty prefix, ne stops responding. I added a guard to `actions.c` in `case AUTOCOMPLETE_A` so that it returns if `strlen(p)` is zero and it works as I want it to, but maybe you prefer some other fix.

**Comment by vigna** [comment]
Oh wow. I'm stunned we never hit this before. Can you suggest a replication path? With 3.3.1 I'm trying to make it hang but I'm unable to do it.

**Comment by soveran** [comment]
I will share a file tonight, along with the steps to reproduce it. Thanks!

**Comment by soveran** [comment]
OK, there are two factors: autocomplete has to be executed without a prefix and the file must contain some unicode character. For example:

```
foo ≠ bar
_
```

(Where `_` represents the cursor)

If I then try to autocomplete, the program hangs. My workaround of not allowing autocomplete with an empty prefix did not address the real issue.

**Comment by vigna** [comment]
OK, there must be something weird happening with UTF-8 encoding...

**Comment by utoddl** [comment]
#89 should address this issue.

**Comment by soveran** [comment]
I've just tested it and it looks like it is solved 👏
