### ISSUE TITLE
Table of contents at the end?

### ISSUE THREAD

**Issue by polluks2** [vigna/ne#92]
https://github.com/vigna/ne/blob/5c079f0fccd6244925385aa4bb055fbc776a8c42/doc/ne.texinfo#L6278

**Comment by vigna** [comment]
Sorry, can you be more descriptive?

**Comment by polluks2** [comment]
Well, TOC of ne.pdf is at the end. I don't know why.

**Comment by vigna** [comment]
Ahem. Oops. Interesting point. Why ever did we do it that way? Todd, do you have any memory? It's in fact quite weird.

**Comment by utoddl** [comment]
No, sorry. Perhaps it has something to do with the bit that reads the docs the build the command tables and help pages? The git history doesn't go back that far. I have no clue.

**Comment by vigna** [comment]
OK, I moved it to the start. Thanks @polluks2 !
